"""Registro central de schemas Pydantic."""
from src.schemas.common import (
    ErrorResponse,
    PaginatedResponse,
    PaginationParams,
)
from src.schemas.costos import (
    ActividadCreate,
    ActividadRead,
    ActividadUpdate,
    CicloProductivoCreate,
    CicloProductivoRead,
    CicloProductivoUpdate,
    CostoActividadCreate,
    CostoActividadRead,
    CultivoCreate,
    CultivoRead,
    CultivoUpdate,
    FincaCreate,
    FincaRead,
    FincaUpdate,
    LoteCreate,
    LoteRead,
    LoteUpdate,
)
from src.schemas.inventario import (
    AlmacenCreate,
    AlmacenRead,
    CategoriaInsumoCreate,
    CategoriaInsumoRead,
    InsumoCreate,
    InsumoRead,
    InsumoUpdate,
    MovimientoKardexCreate,
    MovimientoKardexRead,
    StockActualRead,
)
from src.schemas.nomina import (
    JornaleroCreate,
    JornaleroRead,
    JornaleroUpdate,
    LaborCreate,
    LaborRead,
    LaborUpdate,
    LiquidacionCreate,
    LiquidacionRead,
    NovedadNominaCreate,
    NovedadNominaRead,
)
from src.schemas.tenancy import (
    TenantCreate,
    TenantRead,
    TenantUpdate,
    UsuarioCreate,
    UsuarioRead,
    UsuarioUpdate,
)

__all__ = [
    # Common
    "PaginationParams",
    "PaginatedResponse",
    "ErrorResponse",
    # Tenancy
    "TenantCreate",
    "TenantRead",
    "TenantUpdate",
    "UsuarioCreate",
    "UsuarioRead",
    "UsuarioUpdate",
    # Costos
    "FincaCreate",
    "FincaRead",
    "FincaUpdate",
    "LoteCreate",
    "LoteRead",
    "LoteUpdate",
    "CultivoCreate",
    "CultivoRead",
    "CultivoUpdate",
    "CicloProductivoCreate",
    "CicloProductivoRead",
    "CicloProductivoUpdate",
    "ActividadCreate",
    "ActividadRead",
    "ActividadUpdate",
    "CostoActividadCreate",
    "CostoActividadRead",
    # Inventario
    "CategoriaInsumoCreate",
    "CategoriaInsumoRead",
    "AlmacenCreate",
    "AlmacenRead",
    "InsumoCreate",
    "InsumoRead",
    "InsumoUpdate",
    "StockActualRead",
    "MovimientoKardexCreate",
    "MovimientoKardexRead",
    # Nómina
    "JornaleroCreate",
    "JornaleroRead",
    "JornaleroUpdate",
    "LaborCreate",
    "LaborRead",
    "LaborUpdate",
    "LiquidacionCreate",
    "LiquidacionRead",
    "NovedadNominaCreate",
    "NovedadNominaRead",
]
